apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-notifications
  namespace: observability
type: Opaque
stringData:
  gmail-app-password: YOUR_GMAIL_APP_PASSWORD
  slack-webhook-url: https://hooks.slack.com/services/REPLACE/THIS/URL